export const FORM_CONTENT_PADDING = 16;
export const FORM_CONTENT_BOTTOM_PADDING = 24;
export const TOOLBAR_KEYBOARD_GAP_IOS = 8;
export const TOOLBAR_KEYBOARD_GAP_ANDROID = 35;
export const TOOLBAR_INITIAL_HEIGHT = 56;
